# Site settings
author: Jeffrey currie
title: Journey to flatiron
header-img: img/home-bg.png
email: taycurrie@gmail.com
copyright_name: Jeffrey currie
description: > # this means to ignore newlines until "baseurl:"
  Reasoning behind the decision 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  taycurrie

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
